version: "3.5"

services:
  rnode:
    image: rchain/rnode:v0.9.25.1
    user: root
    container_name: rnode
    ports:
      - 40400:40400
      - 40404:40404
    command: 
      -XX:+HeapDumpOnOutOfMemoryError 
      -XX:HeapDumpPath=/var/lib/rnode-diag/current/heapdump_OOM.hprof 
      -XX:+ExitOnOutOfMemoryError 
      -XX:ErrorFile=/var/lib/rnode-diag/current/hs_err.log 
      -Dlogback.configurationFile=/var/lib/rnode-static/logback.xml 
      -XX:MaxRAMPercentage=75
      -XX:MaxDirectMemorySize=1g
      run 
      --host ${HOST_NAME}
      --network-id mainnet 
      --shard-name root
      --bootstrap rnode://487e2c0c519b450b61253dea0a23b4d184a50089@node0.root-shard.mainnet.rchain.coop?protocol=40400&discovery=40404
      --finalization-rate 1
      --fault-tolerance-threshold -1
      --synchrony-constraint-threshold 0.99
      --max-number-of-parents 1
      --api-max-blocks-limit=100
      --api-enable-reporting
      --fork-choice-stale-threshold 30minutes
      --fork-choice-check-if-stale-interval 30minutes
    volumes:
      - /var/lib/rnode/:/var/lib/rnode/
      - /var/lib/rnode-diag/:/var/lib/rnode-diag/
      - /var/lib/rnode-static/:/var/lib/rnode-static/:ro

########################################################################
  revproxy:
    image: nginx
    container_name: revproxy
    ports:
      - 443:443
      - 40401:40401
      - 40403:40403
      - 40411:40411
    volumes:
      - /var/lib/rnode-static/nginx:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/lib/rnode-diag/current/nginx:/var/log/nginx
    restart: always

########################################################################
  logspout:
    image: gliderlabs/logspout
    container_name: logspout
    ports:
      - 8181:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
