#!/bin/bash
set -e
source "$(dirname $0)/functions"

echo "Proposing"
ret=0
output="$(python3 $INSTALL_DIR/scripts/propose.py 2>&1)" || ret=$?

if [[ $ret -ne 0 && "$output" == *NoNewDeploys* ]]; then
	ret=0
fi

if (( ret )); then
	echo "$output" >&2
else
	echo "$output"
fi
exit $ret
