version: "3.3"

services:
  rnode:
    #image: "${RNODE_DOCKER_IMAGE}"
    image: "rchain/rnode-staging:v0.9.24-88-g4eeb9e196"
    user: root
    networks: 
      - rchain-net
    container_name: rnode
    ports:
      - 40400:40400
      - 40402:40402
      - 40404:40404
      - 40405:40405
    command:
      [
        "run" 
        "-c /var/lib/rnode/rnode.conf",
        "--bootstrap rnode://830eabfbe8344d6530f7f4a3637b7bea49448cd9@node0.sandbox.dev.rchain.coop?protocol=40400&discovery=40404",
        "--api-max-blocks-limit=100",
        "--api-enable-reporting",
        "-J-Xss5m -J-Xms4g -J-Xmx8g",
        "-XX:MaxDirectMemorySize=1g",
        "-XX:+HeapDumpOnOutOfMemoryError",
        "-XX:HeapDumpPath=/var/lib/rnode-diag/current/heapdump_OOM.hprof",
        "-XX:+ExitOnOutOfMemoryError",
        "-XX:ErrorFile=/var/lib/rnode-diag/current/hs_err.log",
        "-XX:MaxJavaStackTraceDepth=100000:",
        "-Djdk.nio.maxCachedBufferSize=262144",
        "-Dlogback.configurationFile=/var/lib/rnode/conf/logback.xml"
      ]
    volumes:
      - /var/lib/rnode/:/var/lib/rnode/
      - /var/lib/rnode-diag/:/var/lib/rnode-diag/
      - /var/lib/rnode-static/:/var/lib/rnode-static/:ro
      - /opt/YourKit-JavaProfiler:/opt/YourKit-JavaProfiler:ro

########################################################################
  revproxy:
    image: nginx
    networks: 
      - rchain-net
    container_name: revproxy
    ports:
      - 443:443
      - 40401:40401
      - 40403:40403
      - 40411:40411
    volumes:
      - /var/lib/rnode-static/nginx:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/lib/rnode-diag/current/nginx:/var/log/nginx

########################################################################
  logspout:
    image: gliderlabs/logspout
    container_name: logspout
    ports:
      - 8181:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

########################################################################
networks:
  rchain-net:

